### ISSUE TITLE
fmin is not equal to evaluated xmin

### ISSUE THREAD

**Issue by r456r** [numericalalgorithmsgroup/dfols#12]
Hi,  I have a complicated gap function with 72 decision variables mapped to produce a 1d scalar. At the solution, the result shows that 
f(xmin) = 9.816218917e-05
But when I input xmin into my gap function, I get 0.009907. The good thing is I already know that my global optimum lies exactly at 0.
Where lies the difference? I do not get it as I maybe making some mistakes in interpretation. I did the following:

# Path A  is Link 10,11     Route Travel time is 16.64              Route flow is 1906.9
# Path B is link 10,9,7     Route Travel time is 19.38              Route flow is 0
# Path C is link 8,6,7      Route Travel time is 19.04              Route flow is 967
# Path D is link 8,5        Route Travel time is 19.04              Route flow is 967
# Path E is link 8,3,4      Route Travel time is 18.24              Route flow is 159.1 
def fun(x):
    
    u_27= x[0];f6_ABCDE= x[1];f7_ABCD= x[2];f8_ABCE= x[3]
    f10_ACDE= x[4];f12_ABC= x[5];f15_ACD= x[6];f16_ACE= x[7]
    f17_ADE= x[8];f18_BCD= x[9];f19_BCE= x[10];f20_BDE= x[11];f21_CDE= x[12];f23_AC= x[13];f24_AD= x[14]
    f25_AE= x[15];f29_CD= x[16];f30_CE= x[17];f31_DE= x[18]
    alpha2_ABCDE= x[19];beta2__ABCDE= x[20];kappa2__ABCDE= x[21]
    delta2__ABCDE= x[22];eta2__ABCDE= x[23];alpha3_ABCD= x[24];beta3_ABCD= x[25];kappa3_ABCD= x[26];delta3_ABCD= x[27]
    alpha4_ABCE= x[28];beta4_ABCE= x[29];kappa4_ABCE= x[30];eta3_ABCE= x[31]
    alpha6_ACDE= x[32];kappa5_ACDE= x[33];delta5_ACDE= x[34];eta5_ACDE= x[35]
    alpha7_ABC= x[36];beta7_ABC= x[37];kappa7_ABC= x[38]
    alpha10_ACD= x[39];kappa8__ACD= x[40];delta8__ACD= x[41];alpha11_ACE= x[42];kappa9_ACE= x[43]
    eta8__ACE= x[44];alpha12_ADE= x[45];delta9_ADE= x[46];eta9_ADE= x[47];beta10_BCD= x[48];kappa10_BCD= x[49]
    delta10_BCD= x[50];beta11_BCE= x[51];kappa11_BCE= x[52];eta10_BCE= x[53];beta12_BDE= x[54];delta11_BDE= x[55]
    eta11_BDE= x[56];kappa12_CDE= x[57];delta12_CDE= x[58];eta12_CDE= x[59]
    alpha14_AC= x[60];kappa13_AC= x[61];alpha15_AD= x[62];delta13_AD= x[63];alpha16_AE= x[64];eta13_AE= x[65]
    
    kappa15_CD= x[66];delta15_CD= x[67];kappa16_CE= x[68];eta15_CE= x[69];delta16_DE= x[70];eta16_DE= x[71];constant=100
    
    # Travel time on each combination
    
    t_ABCDE= alpha2_ABCDE*16.64 + beta2__ABCDE*19.38 + kappa2__ABCDE*19.04 +  delta2__ABCDE* 19.04 +  eta2__ABCDE*18.24
    t_ABCD=alpha3_ABCD*16.64 +beta3_ABCD*19.38 +kappa3_ABCD*19.04 + delta3_ABCD*19.04
    t_ABCE=alpha4_ABCE*16.64 +beta4_ABCE*19.38 + kappa4_ABCE*19.04 +eta3_ABCE*18.24
    
    t_ACDE=alpha6_ACDE*16.64 + kappa5_ACDE*19.04 + delta5_ACDE*19.04 + eta5_ACDE*18.24
    
    t_ABC=alpha7_ABC*16.64 + beta7_ABC*19.38 + kappa7_ABC*19.04
    t_ACD=alpha10_ACD*16.64 + kappa8__ACD*19.04 + delta8__ACD*19.04 
    t_ACE=alpha11_ACE*16.64 + kappa9_ACE*19.04 + eta8__ACE*18.24
    t_ADE=alpha12_ADE*16.64 + delta9_ADE*19.04 + eta9_ADE*18.24
    t_BCD=beta10_BCD*19.38 + kappa10_BCD*19.04 + delta10_BCD*19.04
    t_BCE=beta11_BCE*19.38 + kappa11_BCE*19.04 + eta10_BCE*18.24
    t_BDE=beta12_BDE*19.38 + delta11_BDE*19.04 + eta11_BDE*18.24
    t_CDE=kappa12_CDE*19.04 + delta12_CDE*19.04 + eta12_CDE*18.24
    t_AC=alpha14_AC*16.64 + kappa13_AC*19.04
    t_AD=alpha15_AD*16.64 + delta13_AD*19.04
    t_AE=alpha16_AE*16.64 + eta13_AE*18.24
    t_CD=kappa15_CD*19.04 + delta15_CD*19.04
    t_CE=kappa16_CE*19.04 + eta15_CE*18.24
    t_DE=delta16_DE*19.04 + eta16_DE*18.24
    
    # Here are: Path time - AVT
    FfABCDE=t_ABCDE-u_27; FfABCD=t_ABCD-u_27 
    FfABCE= t_ABCE-u_27; FfACDE=t_ACDE-u_27
    FfABC=t_ABC-u_27;    FfACD=t_ACD-u_27; FfACE=t_ACE-u_27; FfADE=t_ADE-u_27
    FfBCD=t_BCD-u_27; FfBCE=t_BCE-u_27; FfBDE=t_BDE-u_27; FfCDE=t_CDE-u_27
    FfAC=t_AC-u_27; FfAD=t_AD-u_27 
    FfAE=t_AE-u_27
    FfCD=t_CD-u_27; FfCE=t_CE-u_27
    FfDE=t_DE-u_27
    
    # Here are: Proprotions - 1
    
    Fu_ABCDE=alpha2_ABCDE+beta2__ABCDE+kappa2__ABCDE+delta2__ABCDE+eta2__ABCDE-1
    Fu_ABCD=alpha3_ABCD+beta3_ABCD+kappa3_ABCD+ delta3_ABCD-1
    Fu_ABCE=alpha4_ABCE+beta4_ABCE+ kappa4_ABCE+eta3_ABCE-1
    
    Fu_ACDE=alpha6_ACDE+kappa5_ACDE+ delta5_ACDE + eta5_ACDE-1
    
    Fu_ABC=alpha7_ABC+beta7_ABC+kappa7_ABC-1
    Fu_ACD=alpha10_ACD+kappa8__ACD+delta8__ACD-1
    Fu_ACE=alpha11_ACE+kappa9_ACE+eta8__ACE-1; Fu_ADE=alpha12_ADE+delta9_ADE+eta9_ADE-1
    Fu_BCD=beta10_BCD+kappa10_BCD+delta10_BCD-1; Fu_BCE=beta11_BCE+kappa11_BCE+eta10_BCE-1
    Fu_BDE=beta12_BDE+delta11_BDE+eta11_BDE-1; Fu_CDE=kappa12_CDE+delta12_CDE+eta12_CDE-1
    Fu_AC=alpha14_AC+kappa13_AC-1; Fu_AD=alpha15_AD+delta13_AD-1
    Fu_AE=alpha16_AE+eta13_AE-1
    Fu_CD=kappa15_CD+delta15_CD-1; Fu_CE=kappa16_CE+eta15_CE-1
    Fu_DE=delta16_DE+eta16_DE-1
    
    # Here are flow constraints: Fe1A, Fe2B, Fe3C, Fe4D, Fe5E
    
    Fe1=alpha2_ABCDE*f6_ABCDE +alpha3_ABCD*f7_ABCD +alpha4_ABCE*f8_ABCE  +alpha6_ACDE*f10_ACDE +alpha7_ABC*f12_ABC  +alpha10_ACD*f15_ACD +alpha11_ACE*f16_ACE +alpha12_ADE*f17_ADE  +alpha14_AC*f23_AC +alpha15_AD*f24_AD +alpha16_AE*f25_AE -1906.9
      
    Fe2=beta2__ABCDE*f6_ABCDE + beta3_ABCD*f7_ABCD +beta4_ABCE*f8_ABCE +beta7_ABC*f12_ABC +beta10_BCD*f18_BCD +beta11_BCE*f19_BCE +beta12_BDE*f20_BDE -0
    
    Fe3=kappa2__ABCDE*f6_ABCDE +kappa3_ABCD*f7_ABCD +kappa4_ABCE*f8_ABCE +kappa5_ACDE*f10_ACDE +kappa7_ABC*f12_ABC +kappa8__ACD*f15_ACD +kappa9_ACE*f16_ACE +kappa10_BCD*f18_BCD + kappa11_BCE*f19_BCE +kappa12_CDE*f21_CDE +kappa13_AC*f23_AC +kappa15_CD*f29_CD +kappa16_CE*f30_CE -967
    
    Fe4=delta2__ABCDE*f6_ABCDE +delta3_ABCD*f7_ABCD +delta5_ACDE*f10_ACDE  +delta8__ACD*f15_ACD +delta9_ADE*f17_ADE +delta10_BCD*f18_BCD +delta11_BDE*f20_BDE +delta12_CDE*f21_CDE +delta13_AD*f24_AD +delta15_CD*f29_CD +delta16_DE*f31_DE -967
    
    Fe5=eta2__ABCDE*f6_ABCDE +eta3_ABCE*f8_ABCE  +eta5_ACDE*f10_ACDE +eta8__ACE*f16_ACE +eta9_ADE*f17_ADE +eta10_BCE*f19_BCE +eta11_BDE*f20_BDE +eta12_CDE*f21_CDE +eta13_AE*f25_AE  +eta15_CE*f30_CE +eta16_DE*f31_DE -159.1
    
    
    ############# Summation of flow constraints######
    F_flow=f6_ABCDE+f7_ABCD+f8_ABCE+f10_ACDE+f12_ABC+f15_ACD+f16_ACE+f17_ADE+f18_BCD+f19_BCE+f20_BDE+f21_CDE+f23_AC+f24_AD+f25_AE+f29_CD+f30_CE+f31_DE-4000
    
    # Here are all the phi releated to flow groups and time:    Flow group * (Path time - AVT) = 0
    # 31 combination so 31 groups so 31 phis
    
    phi6= np.sqrt(f6_ABCDE**2 + FfABCDE**2) - f6_ABCDE - FfABCDE
    phi7= np.sqrt(f7_ABCD**2 + FfABCD**2) - f7_ABCD - FfABCD
    phi8= np.sqrt(f8_ABCE**2 + FfABCE**2) - f8_ABCE - FfABCE
    
    phi10= np.sqrt(f10_ACDE**2 + FfACDE**2) - f10_ACDE - FfACDE
    
    phi12= np.sqrt(f12_ABC**2 + FfABC**2) - f12_ABC - FfABC
   
    phi15= np.sqrt(f15_ACD**2 + FfACD**2) - f15_ACD - FfACD
    phi16= np.sqrt(f16_ACE**2 + FfACE**2) - f16_ACE - FfACE
    phi17= np.sqrt(f17_ADE**2 + FfADE**2) - f17_ADE - FfADE
    phi18= np.sqrt(f18_BCD**2 + FfBCD**2) - f18_BCD - FfBCD
    phi19= np.sqrt(f19_BCE**2 + FfBCE**2) - f19_BCE - FfBCE
    phi20= np.sqrt(f20_BDE**2 + FfBDE**2) - f20_BDE - FfBDE
    phi21= np.sqrt(f21_CDE**2 + FfCDE**2) - f21_CDE - FfCDE
    
    phi23= np.sqrt(f23_AC**2 + FfAC**2) - f23_AC - FfAC
    phi24= np.sqrt(f24_AD**2 + FfAD**2) - f24_AD - FfAD
    phi25= np.sqrt(f25_AE**2 + FfAE**2) - f25_AE - FfAE
    
    phi29= np.sqrt(f29_CD**2 + FfCD**2) - f29_CD - FfCD
    phi30= np.sqrt(f30_CE**2 + FfCE**2) - f30_CE - FfCE
    phi31= np.sqrt(f31_DE**2 + FfDE**2) - f31_DE - FfDE
    
    
   
    # Here are all the phi releated to proportions -1  : flow (alpha + beta + kappa +.....-1) = 0
    # 31 combination so 31 groups so 31 phis
    phi37= np.sqrt(Fu_ABCDE**2 + f6_ABCDE**2) - Fu_ABCDE - f6_ABCDE
    phi38= np.sqrt(Fu_ABCD**2 + f7_ABCD**2) - Fu_ABCD - f7_ABCD
    phi39= np.sqrt(Fu_ABCE**2 + f8_ABCE**2) - Fu_ABCE - f8_ABCE
    
    phi41= np.sqrt(Fu_ACDE**2 + f10_ACDE**2) - Fu_ACDE - f10_ACDE
    
    phi43= np.sqrt(Fu_ABC**2 + f12_ABC**2) - Fu_ABC - f12_ABC
   
    phi46= np.sqrt(Fu_ACD**2 + f15_ACD**2) - Fu_ACD - f15_ACD
    phi47= np.sqrt(Fu_ACE**2 + f16_ACE**2) - Fu_ACE - f16_ACE
    phi48= np.sqrt(Fu_ADE**2 + f17_ADE**2) - Fu_ADE - f17_ADE
    phi49= np.sqrt(Fu_BCD**2 + f18_BCD**2) - Fu_BCD - f18_BCD
    phi50= np.sqrt(Fu_BCE**2 + f19_BCE**2) - Fu_BCE - f19_BCE
    phi51= np.sqrt(Fu_BDE**2 + f20_BDE**2) - Fu_BDE - f20_BDE
    phi52= np.sqrt(Fu_CDE**2 + f21_CDE**2) - Fu_CDE - f21_CDE
    
    phi54= np.sqrt(Fu_AC**2 + f23_AC**2) - Fu_AC - f23_AC
    phi55= np.sqrt(Fu_AD**2 + f24_AD**2) - Fu_AD - f24_AD
    phi56= np.sqrt(Fu_AE**2 + f25_AE**2) - Fu_AE - f25_AE
    
    phi60= np.sqrt(Fu_CD**2 + f29_CD**2) - Fu_CD - f29_CD
    phi61= np.sqrt(Fu_CE**2 + f30_CE**2) - Fu_CE - f30_CE
    phi62= np.sqrt(Fu_DE**2 + f31_DE**2) - Fu_DE - f31_DE
    
    
    # Here are all the phi releated to path flow constraints:     u (alpha1*ta +alpha2*tab- fa)=0
    # 5 paths so 5 phis
    phi63= np.sqrt(u_27**2 + Fe1**2) - u_27 - Fe1
    phi64= np.sqrt(u_27**2 + Fe2**2) - u_27 - Fe2
    phi65= np.sqrt(u_27**2 + Fe3**2) - u_27 - Fe3
    phi66= np.sqrt(u_27**2 + Fe4**2) - u_27 - Fe4
    phi67= np.sqrt(u_27**2 + Fe5**2) - u_27 - Fe5
    
    ############ Trial for another phi #############    u(sum of all flows - total demand)=0
    phi68= np.sqrt(F_flow**2 + constant**2) - F_flow - constant
    
    ##############################TRIAL FOR ALPHA(SUM OF FLOWS - DEMAND)
    
    
    phi74=np.sqrt(alpha2_ABCDE**2 + F_flow**2) - alpha2_ABCDE - F_flow
    phi75=np.sqrt(beta2__ABCDE**2 + F_flow**2) - beta2__ABCDE - F_flow
    phi76=np.sqrt(kappa2__ABCDE**2 + F_flow**2) - kappa2__ABCDE - F_flow
    phi77=np.sqrt(delta2__ABCDE**2 + F_flow**2) - delta2__ABCDE - F_flow
    phi78=np.sqrt(eta2__ABCDE**2 + F_flow**2) - eta2__ABCDE - F_flow
    phi79=np.sqrt(alpha3_ABCD**2 + F_flow**2) - alpha3_ABCD - F_flow
    phi80=np.sqrt(beta3_ABCD**2 + F_flow**2) - beta3_ABCD - F_flow
    phi81=np.sqrt(kappa3_ABCD**2 + F_flow**2) - kappa3_ABCD - F_flow
    phi82=np.sqrt(delta3_ABCD**2 + F_flow**2) - delta3_ABCD - F_flow
    phi83=np.sqrt(alpha4_ABCE**2 + F_flow**2) - alpha4_ABCE - F_flow
    phi84=np.sqrt(beta4_ABCE**2 + F_flow**2) - beta4_ABCE - F_flow
    phi85=np.sqrt(kappa4_ABCE**2 + F_flow**2) - kappa4_ABCE - F_flow
    phi86=np.sqrt(eta3_ABCE**2 + F_flow**2) - eta3_ABCE - F_flow
   
    phi91=np.sqrt(alpha6_ACDE**2 + F_flow**2) - alpha6_ACDE - F_flow
    phi92=np.sqrt(kappa5_ACDE**2 + F_flow**2) - kappa5_ACDE - F_flow
    phi93=np.sqrt(delta5_ACDE**2 + F_flow**2) - delta5_ACDE - F_flow
    phi94=np.sqrt(eta5_ACDE**2 + F_flow**2) - eta5_ACDE - F_flow
    
    phi99=np.sqrt(alpha7_ABC**2 + F_flow**2) - alpha7_ABC - F_flow
    phi100=np.sqrt(beta7_ABC**2 + F_flow**2) - beta7_ABC - F_flow
    phi101=np.sqrt(kappa7_ABC**2 + F_flow**2) - kappa7_ABC - F_flow
    
    
    phi108=np.sqrt(alpha10_ACD**2 + F_flow**2) - alpha10_ACD - F_flow
    phi109=np.sqrt(kappa8__ACD**2 + F_flow**2) - kappa8__ACD - F_flow
    phi110=np.sqrt(delta8__ACD**2 + F_flow**2) - delta8__ACD - F_flow
    phi111=np.sqrt(alpha11_ACE**2 + F_flow**2) - alpha11_ACE - F_flow
    phi112=np.sqrt(kappa9_ACE**2 + F_flow**2) - kappa9_ACE - F_flow
    phi113=np.sqrt(eta8__ACE**2 + F_flow**2) - eta8__ACE - F_flow
    phi114=np.sqrt(alpha12_ADE**2 + F_flow**2) - alpha12_ADE - F_flow
    phi115=np.sqrt(delta9_ADE**2 + F_flow**2) - delta9_ADE - F_flow
    phi116=np.sqrt(eta9_ADE**2 + F_flow**2) - eta9_ADE - F_flow
    phi117=np.sqrt(beta10_BCD**2 + F_flow**2) - beta10_BCD - F_flow
    phi118=np.sqrt(kappa10_BCD**2 + F_flow**2) - kappa10_BCD - F_flow
    
    
    
    phi119=np.sqrt(beta11_BCE**2 + F_flow**2) - beta11_BCE - F_flow
    phi120=np.sqrt(kappa11_BCE**2 + F_flow**2) - kappa11_BCE - F_flow
    phi121=np.sqrt(eta10_BCE**2 + F_flow**2) - eta10_BCE - F_flow
    phi122=np.sqrt(beta12_BDE**2 + F_flow**2) - beta12_BDE - F_flow
    phi123=np.sqrt(delta11_BDE**2 + F_flow**2) - delta11_BDE - F_flow
    phi124=np.sqrt(eta11_BDE**2 + F_flow**2) - eta11_BDE - F_flow
    phi125=np.sqrt(kappa12_CDE**2 + F_flow**2) - kappa12_CDE - F_flow
    phi126=np.sqrt(delta12_CDE**2 + F_flow**2) - delta12_CDE - F_flow
    phi127=np.sqrt(eta12_CDE**2 + F_flow**2) - eta12_CDE - F_flow
    
    phi130=np.sqrt(alpha14_AC**2 + F_flow**2) - alpha14_AC - F_flow
    phi131=np.sqrt(kappa13_AC**2 + F_flow**2) - kappa13_AC - F_flow
    phi132=np.sqrt(alpha15_AD**2 + F_flow**2) - alpha15_AD - F_flow
    phi133=np.sqrt(delta13_AD**2 + F_flow**2) - delta13_AD - F_flow
    phi134=np.sqrt(alpha16_AE**2 + F_flow**2) - alpha16_AE - F_flow
    phi135=np.sqrt(eta13_AE**2 + F_flow**2) - eta13_AE - F_flow
    
    
    phi142=np.sqrt(kappa15_CD**2 + F_flow**2) - kappa15_CD - F_flow
    phi143=np.sqrt(delta15_CD**2 + F_flow**2) - delta15_CD - F_flow
    phi144=np.sqrt(kappa16_CE**2 + F_flow**2) - kappa16_CE - F_flow
    phi145=np.sqrt(eta15_CE**2 + F_flow**2) - eta15_CE - F_flow
    phi146=np.sqrt(delta16_DE**2 + F_flow**2) - delta16_DE - F_flow
    phi147=np.sqrt(eta16_DE**2 + F_flow**2) - eta16_DE - F_flow
    phi148=np.sqrt(delta10_BCD**2 + F_flow**2) - delta10_BCD - F_flow
    
    
    
    # Now for all the zetas of gap function
    zeta6= 0.5*(phi6)**2; zeta7= 0.5*(phi7)**2; zeta8= 0.5*(phi8)**2; zeta10= 0.5*(phi10)**2
    zeta12= 0.5*(phi12)**2;zeta15= 0.5*(phi15)**2
    zeta16= 0.5*(phi16)**2; zeta17= 0.5*(phi17)**2;zeta18= 0.5*(phi18)**2;zeta19= 0.5*(phi19)**2;zeta20= 0.5*(phi20)**2
    zeta21= 0.5*(phi21)**2; zeta23= 0.5*(phi23)**2;zeta24= 0.5*(phi24)**2;zeta25= 0.5*(phi25)**2
    zeta29= 0.5*(phi29)**2;zeta30= 0.5*(phi30)**2
    zeta31= 0.5*(phi31)**2
    zeta37= 0.5*(phi37)**2;zeta38= 0.5*(phi38)**2;zeta39= 0.5*(phi39)**2
    zeta41= 0.5*(phi41)**2; zeta43= 0.5*(phi43)**2
    zeta46= 0.5*(phi46)**2; zeta47= 0.5*(phi47)**2;zeta48= 0.5*(phi48)**2;zeta49= 0.5*(phi49)**2;zeta50= 0.5*(phi50)**2
    zeta51= 0.5*(phi51)**2; zeta52= 0.5*(phi52)**2;zeta54= 0.5*(phi54)**2;zeta55= 0.5*(phi55)**2
    zeta56= 0.5*(phi56)**2; zeta60= 0.5*(phi60)**2
    zeta61= 0.5*(phi61)**2; zeta62= 0.5*(phi62)**2;zeta63= 0.5*(phi63)**2;zeta64= 0.5*(phi64)**2;zeta65= 0.5*(phi65)**2
    zeta66= 0.5*(phi66)**2; zeta67= 0.5*(phi67)**2
    
    ############ Trial for another zeta ###########33
    zeta68= 0.5*(phi68)**2
    
    #####################TRIAL FOR  zeta       ALPHA(SUM OF FLOWS - DEMAND)
   
    zeta74= 0.5*(phi74)**2; zeta75= 0.5*(phi75)**2; zeta76= 0.5*(phi76)**2; zeta77= 0.5*(phi77)**2; zeta78= 0.5*(phi78)**2
    zeta79= 0.5*(phi79)**2; zeta80= 0.5*(phi80)**2; zeta81= 0.5*(phi81)**2; zeta82= 0.5*(phi82)**2; zeta83= 0.5*(phi83)**2
    zeta84= 0.5*(phi84)**2; zeta85= 0.5*(phi85)**2; zeta86= 0.5*(phi86)**2
    zeta91= 0.5*(phi91)**2; zeta92= 0.5*(phi92)**2; zeta93= 0.5*(phi93)**2
    zeta94= 0.5*(phi94)**2
    zeta99= 0.5*(phi99)**2; zeta100= 0.5*(phi100)**2; zeta101= 0.5*(phi101)**2
    zeta108= 0.5*(phi108)**2
    zeta109= 0.5*(phi109)**2; zeta110= 0.5*(phi110)**2;zeta111= 0.5*(phi111)**2;zeta112= 0.5*(phi112)**2;zeta113= 0.5*(phi113)**2
    zeta114= 0.5*(phi114)**2; zeta115= 0.5*(phi115)**2;zeta116= 0.5*(phi116)**2;zeta117= 0.5*(phi117)**2;zeta118= 0.5*(phi118)**2
    zeta119= 0.5*(phi119)**2; zeta120= 0.5*(phi120)**2;zeta121= 0.5*(phi121)**2;zeta122= 0.5*(phi122)**2;zeta123= 0.5*(phi123)**2
    zeta124= 0.5*(phi124)**2; zeta125= 0.5*(phi125)**2;zeta126= 0.5*(phi126)**2;zeta127= 0.5*(phi127)**2
    zeta130= 0.5*(phi130)**2;zeta131= 0.5*(phi131)**2;zeta132= 0.5*(phi132)**2;zeta133= 0.5*(phi133)**2
    zeta134= 0.5*(phi134)**2; zeta135= 0.5*(phi135)**2
    zeta142= 0.5*(phi142)**2; zeta143= 0.5*(phi143)**2;zeta144= 0.5*(phi144)**2;zeta145= 0.5*(phi145)**2
    zeta146= 0.5*(phi146)**2; zeta147= 0.5*(phi147)**2;zeta148= 0.5*(phi148)**2 
     
    g = zeta6+zeta7+zeta8+zeta10+zeta12+zeta15+zeta16+zeta17+zeta18+zeta19+zeta20+zeta21+zeta23+zeta24+zeta25+zeta29+zeta30+zeta31+zeta37+zeta38+zeta39+zeta41+zeta43+zeta46+zeta47+zeta48+zeta49+zeta50+zeta51+zeta52+zeta54+zeta55+zeta56+zeta60+zeta61+zeta62+zeta63+zeta64+zeta65+zeta66+zeta67+zeta68+zeta74+zeta75+zeta76+zeta77+zeta78+zeta79+zeta80+zeta81+zeta82+zeta83+zeta84+zeta85+zeta86+zeta91+zeta92+zeta93+zeta94+zeta99+zeta100+zeta101+zeta108+zeta109+zeta110+zeta111+zeta112+zeta113+zeta114+zeta115+zeta116+zeta117+zeta118+zeta119+zeta120+zeta121+zeta122+zeta123+zeta124+zeta125+zeta126+zeta127+zeta130+zeta131+zeta132+zeta133+zeta134+zeta135+zeta142+zeta143+zeta144+zeta145+zeta146+zeta147+zeta148 
    
    return np.array([g])

x=np.array([17.8647308,
327.353944,
469.332157,
341.924358,
332.719177,
128.361731,
246.24824,
116.04051,
178.557758,
181.125954,
179.780686,
12.212456,
132.584912,
384.943575,
494.856956,
189.105998,
93.4209361,
191.430671,
-1.21E-09,
0.569849426,
1.59E-08,
0.037992577,
0.40219547,
2.11E-08,
0.616568978,
2.25E-08,
0.034588349,
0.364737696,
0.583596327,
1.61E-08,
0.428169136,
2.16E-08,
0.596635426,
0.027056362,
0.389712381,
2.13E-08,
0.507066907,
6.30E-09,
0.495101423,
0.572368688,
0.252372569,
0.185624275,
0.526870309,
0.477788853,
7.54E-09,
0.537319776,
0.468646581,
1.13E-08,
7.78E-09,
0.356968006,
0.581454739,
7.61E-09,
0.837659349,
0.105170911,
-1.06E-09,
-7.56E-10,
0.979488703,
0.350337265,
0.282578698,
0.318872102,
0.599331141,
0.414405578,
0.636490112,
0.38190432,
0.65640573,
0.380457124,
0.153475103,
0.784957734,
0.868322983,
0.07316457,
0.09318066,
0.994761024
])

import dfbgn

soln = dfbgn.solve(fun, x, fixed_block=72,rhoend=1e-17, maxfun=2000)
print(soln)
print(soln)

****** DFBGN Results ******
Solution xmin = [ 1.78647308e+01  3.27353944e+02  4.69332157e+02  3.41924358e+02
  3.32719177e+02  1.28361731e+02  2.46248240e+02  1.16040510e+02
  1.78557758e+02  1.81125954e+02  1.79780686e+02  1.22124560e+01
  1.32584912e+02  3.84943575e+02  4.94856956e+02  1.89105998e+02
  9.34209361e+01  1.91430671e+02 -1.20806047e-09  5.69849426e-01
  1.58632430e-08  3.79925770e-02  4.02195470e-01  2.11566062e-08
  6.16568978e-01  2.25643516e-08  3.45883489e-02  3.64737696e-01
  5.83596327e-01  1.60017148e-08  4.28169136e-01  2.15812467e-08
  5.96635426e-01  2.70563620e-02  3.89712381e-01  2.13284259e-08
  5.07066907e-01  6.36715353e-09  4.95101423e-01  5.72368688e-01
  2.52372569e-01  1.85624275e-01  5.26870309e-01  4.77788853e-01
  7.56637460e-09  5.37319776e-01  4.68646581e-01  1.13789897e-08
  7.70050248e-09  3.56968006e-01  5.81454739e-01  7.69466290e-09
  8.37659349e-01  1.05170911e-01 -1.04143229e-09 -7.25275262e-10
  9.79488703e-01  3.50337265e-01  2.82578698e-01  3.18872102e-01
  5.99331141e-01  4.14405578e-01  6.36490112e-01  3.81904320e-01
  6.56405730e-01  3.80457124e-01  1.53475103e-01  7.84957734e-01
  8.68322983e-01  7.31645700e-02  9.31806600e-02  9.94761024e-01]
Residual vector = [0.0099077]
Objective value f(xmin) = 9.816252667e-05
Needed 124 objective evaluations
No approximate Jacobian available
Exit flag = 0
Success: delta has reached rhoend
****************************

Can you kindly explain whether I am doing something wrong?

**Comment by lindonroberts** [comment]
Hi,

The difference is that DFBGN assumes that fun(x) returns a vector, and its internal objective is the sum of squares of this vector.

That is, DFBGN tries to minimize the least-squares function

`f = lambda x: fun(x).T @ fun(x)`

So, what you are seeing is fun(x) returned as the "residual vector", which is the vector [0.0099077] of length one, and then the objective value f(x) is the sum of squares of this value (i.e. 9.81e-5 = 9.91e-3 ** 2).

It depends on your problem, but you need to consider whether you want to minimize fun(x) or the sum of squares of fun(x). If you don't have a sum-of-squares problem structure, then you may want to try my other code [Py-BOBYQA](https://github.com/numericalalgorithmsgroup/pybobyqa), which minimizes fun(x) directly. In that case, you will need to change the return statement to return a float, rather than a numpy array of length 1.
